apiVersion: v1
kind: Service
metadata:
  name: slimserve
  labels:
    service: slimserve
spec:
  type: LoadBalancer
  selector:
    service: slimserve
  ports:
    - name: http-initial
      port: 5000
      targetPort: 8080