apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: slimserve-data
  name: slimserve-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
