apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome
  labels:
    service: adguardhome
spec:
  replicas: 1
  selector:
    matchLabels:
      service: adguardhome
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: adguardhome
    spec:
      hostNetwork: true
      containers:
        - name: adguardhome
          image: adguard/adguardhome:v0.107.63
          volumeMounts:
            - name: adguard-data
              mountPath: /opt/adguardhome/work
            - name: adguard-data
              mountPath: /opt/adguardhome/conf
          ports:
          - containerPort: 53
            name: dns
            protocol: UDP
          - containerPort: 3000
            name: http-initial
          - containerPort: 80
            name: http
            protocol: TCP
      restartPolicy: Always
      volumes:
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-data