apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: adguard-namespace
spec:
  type: LoadBalancer
  selector:
    service: adguardhome
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: http
      port: 1000
      targetPort: 80
    - name: dashboard
      port: 3000
      targetPort: 3000