apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: adguard-namespace
spec:
  type: LoadBalancer
  selector:
    service: adguardhome
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-initial