apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: adguard-data
  name: adguard-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi