apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:latest
          env:
            - name: SEARXNG_BASE_URL
              value: https://search.erffy.me
          volumeMounts:
            - name: searxng-data
              mountPath: /etc/searxng
            - name: searxng-data
              mountPath: /var/cache/searxng
      restartPolicy: Always
      volumes:
        - name: searxng-data
          persistentVolumeClaim:
            claimName: searxng-data