apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: searxng
  name: searxng
  namespace: searxng
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      service: searxng
  template:
    metadata:
      labels:
        service: searxng
    spec:
      containers:
        - name: searxng
          image: searxng/searxng:2025.7.22-5cbf422
          env:
            - name: SEARXNG_BASE_URL
              value: https://search.erffy.me
          volumeMounts:
            - name: searxng-data
              mountPath: /etc/searxng
            - name: searxng-data
              mountPath: /var/cache/searxng
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http-initial
      restartPolicy: Always
      volumes:
        - name: searxng-data
          persistentVolumeClaim:
            claimName: searxng-data