apiVersion: v1
kind: Service
metadata:
  name: searxng-service
  namespace: searxng-namespace
spec:
  type: LoadBalancer
  selector:
    app: searxng
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
      name: http-initial