apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: searxng-data
  name: searxng-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
