apiVersion: v1
kind: Service
metadata:
  name: convertx
  namespace: convertx-namespace
spec:
  type: LoadBalancer
  selector:
    service: convertx
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 3000
      name: http