apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: convertx-data
  name: convertx-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
