apiVersion: v1
kind: Service
metadata:
  name: dashdot-service
  namespace: dashdot-namespace
spec:
  type: LoadBalancer
  selector:
    app: dashdot
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3001
      name: http