apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    service: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: postgresql
    spec:
      containers:
        - name: postgres-db
          image: postgres:14.18
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Q4T16c4mDhwZUBZY!MWG
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data