apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: postgresql-data
  name: postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
