apiVersion: v1
kind: Service
metadata:
  name: picoshare
  namespace: picoshare-namespace
spec:
  type: LoadBalancer
  selector:
    service: picoshare
  ports:
    - name: http
      port: 9000
      targetPort: 4001