apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: picoshare-data
  name: picoshare-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi